# Generated by Django 5.1.4 on 2025-01-11 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_connection_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='DbConnectionModel',
        ),
    ]
