# Generated by Django 5.1.4 on 2025-01-11 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_dbconnectionmodel_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dbconnectionmodel',
            name='unique_name_per_user',
        ),
        migrations.AddField(
            model_name='dbconnectionmodel',
            name='id_name',
            field=models.CharField(default='aecd9eee', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='dbconnectionmodel',
            constraint=models.UniqueConstraint(fields=('user', 'id_name'), name='unique_id_name_per_user'),
        ),
    ]
